import type { StudentContent } from "./types";

export const en: StudentContent = {
  metadata: {
    studentTitle: "My student area",
    studentDescription: "Access materials and classes Paulina shared with you.",
    teacherTitle: "Teacher area",
    teacherDescription: "Manage homework, classes, and student/parent access.",
  },
  portal: {
    backHome: "Back to home",
    myArea: "My area",
    teacherArea: "Teacher area",
    signInTitle: "Sign in to your area",
    signInSubtitle: "Use the email address Paulina invited you with.",
    emailLabel: "Email",
    passwordLabel: "Password",
    signInButton: "Sign in",
    signInError: "Incorrect email or password.",
    logoutLabel: "Log out",
    languageToggleAria: "Change language",
  },
  student: {
    title: "Your classes and homework",
    subtitle: "See the date, time, Meet link, and homework for each class.",
    parentSubtitle: "Classes and homework for {name}",
    emptyTitle: "No classes yet",
    emptyBody: "When Paulina schedules classes or homework, they will show up here.",
    openLabel: "Open material",
    newBadge: "New",
    classesTitle: "Classes",
    upcomingTitle: "Upcoming classes",
    pastTitle: "Past classes",
    undatedTitle: "Other materials",
    scheduledLabel: "Class",
    joinMeetLabel: "Join Meet",
    homeworkLabel: "Homework",
    homeworkEmpty: "No homework for this class yet.",
    statusLabel: "Done?",
    statusPending: "Pending",
    statusDone: "Yes",
    statusNotDone: "No",
    statusPartial: "Partially",
    notesLabel: "Class notes",
    notesPlaceholder: "Write anything you want to remember from class…",
    notesSaved: "Notes saved",
  },
  teacher: {
    title: "Classes and homework",
    subtitle:
      "Pick a student: set their schedule, write homework on each class, and mark whether it was done.",
    selectStudentLabel: "Student",
    selectStudentPlaceholder: "Select a student",
    urlHint:
      "Materials without a class date (Drive, PDF, YouTube). Kept separate from the class table.",
    addTitle: "New extra material",
    titleLabel: "Title",
    titlePlaceholder: "Verb guide",
    descriptionLabel: "Description",
    descriptionPlaceholder: "Optional notes or instructions…",
    urlLabel: "Link (optional)",
    urlPlaceholder: "https://drive.google.com/...",
    urlOptionalHint: "PDF, Drive, or online resource.",
    nextClassHint:
      "Homework goes in each row of the class table. This section is only for undated materials.",
    scheduledAtLabel: "Class date and time",
    meetUrlLabel: "Google Meet link",
    meetUrlPlaceholder: "https://meet.google.com/...",
    addButton: "Save and assign",
    editButton: "Edit",
    saveEditButton: "Save changes",
    cancelEditButton: "Cancel",
    materialsTitle: "Extra materials",
    materialsEmpty: "No extra materials for this student.",
    classesTableTitle: "Class table",
    classesEmpty: "No classes yet. Save a fixed schedule or add a class.",
    homeworkLabel: "Homework for this class",
    homeworkPlaceholder: "Paste the exercise or note book and page…",
    saveHomeworkButton: "Save homework",
    addClassLabel: "Add class",
    addClassButton: "Create class",
    extrasTitle: "Extra materials",
    extrasHint: "Resources without a class date. Not mixed with homework.",
    extrasEmpty: "No extra materials yet.",
    upcomingTitle: "Upcoming",
    pastTitle: "Past",
    searchPlaceholder: "Search materials…",
    searchEmpty: "No materials match your search.",
    deleteLabel: "Delete",
    assignButton: "Assign",
    assignHint: "Assign this material to more students if needed.",
    assignAllLabel: "Assign to all",
    homeworkStatusLabel: "Done?",
    statusPending: "Pending",
    statusDone: "Yes",
    statusNotDone: "No",
    statusPartial: "Partially",
    noStudents: "No students yet. Create them above to get started.",
    scheduleSectionTitle: "Schedule and Meet",
    scheduleSectionHint:
      "Fixed schedule: upcoming classes are generated. Class by class: save Meet only and add each date. The link stays the same.",
    scheduleModeWeekly: "Fixed weekly schedule",
    scheduleModeAdhoc: "Class by class",
    scheduleWeekdayLabel: "Day",
    scheduleTimeLabel: "Time (24h, e.g. 20:00 = 8 pm)",
    scheduleMeetLabel: "Meet (same link every time)",
    scheduleSaveLabel: "Save schedule",
    scheduleActiveLabel: "Generate upcoming classes",
    scheduleSaved: "Schedule saved. Upcoming classes updated.",
    weekdaySunday: "Sunday",
    weekdayMonday: "Monday",
    weekdayTuesday: "Tuesday",
    weekdayWednesday: "Wednesday",
    weekdayThursday: "Thursday",
    weekdayFriday: "Friday",
    weekdaySaturday: "Saturday",
    createStudentTitle: "New student",
    studentNameLabel: "Name",
    studentNamePlaceholder: "Anna Gomez",
    studentEmailLabel: "Email",
    studentEmailPlaceholder: "anna@email.com",
    studentPasswordLabel: "Initial password",
    studentPasswordPlaceholder: "At least 8 characters",
    createStudentButton: "Create student",
    successStudentCreated: "Student created.",
    createParentTitle: "New parent account",
    parentNameLabel: "Name",
    parentNamePlaceholder: "Mary Gomez",
    parentEmailLabel: "Email",
    parentEmailPlaceholder: "mary@email.com",
    parentPasswordLabel: "Initial password",
    parentPasswordPlaceholder: "At least 8 characters",
    parentStudentLabel: "Linked student",
    createParentButton: "Create parent account",
    successParentCreated: "Parent account created.",
    errorStudentName: "Enter a name with at least 2 characters.",
    errorStudentEmail: "Enter a valid email address.",
    errorStudentPassword: "The password must be at least 8 characters.",
    errorParentName: "Enter a name with at least 2 characters.",
    errorParentEmail: "Enter a valid email address.",
    errorParentPassword: "The password must be at least 8 characters.",
    errorParentStudent: "Select a student.",
    successAdded: "Material saved and assigned.",
    successAssigned: "Assignment updated.",
    successUpdated: "Changes saved.",
    successClassAdded: "Class added.",
    errorGeneric: "We could not complete that action. Please try again.",
    errorUrl: "The link must start with https://",
    errorTitle: "Enter a title with at least 2 characters.",
    errorContent: "Add a description or a link.",
    errorClassDate: "Choose a class date and time.",
    navMaterials: "Materials",
    navLeads: "Leads",
    navContacts: "Contacts",
    navEmails: "Emails",
    navSignature: "Signature",
  },
};
