import type { StudentContent } from "./types";

export const en: StudentContent = {
  metadata: {
    studentTitle: "My student area | Bilingual Boost",
    studentDescription: "Access the materials Paulina shared with you.",
    teacherTitle: "Teacher area | Bilingual Boost",
    teacherDescription: "Manage materials and assign them to your students.",
  },
  portal: {
    backHome: "Back to home",
    myArea: "My area",
    teacherArea: "Teacher area",
    signInTitle: "Sign in to your area",
    signInSubtitle: "Use the email address Paulina invited you with.",
  },
  student: {
    title: "Your materials",
    subtitle: "Here are the resources Paulina shared with you.",
    emptyTitle: "No materials yet",
    emptyBody: "When Paulina assigns resources to you, they will show up here.",
    openLabel: "Open material",
    newBadge: "New",
    markDone: "Mark as done",
    markUndone: "Mark as pending",
    doneBadge: "Done",
  },
  teacher: {
    title: "Student materials",
    subtitle: "Add links (for example Google Drive) and assign them to each student.",
    addTitle: "New material",
    titleLabel: "Title",
    titlePlaceholder: "Conversation guide — week 1",
    descriptionLabel: "Description",
    descriptionPlaceholder: "PDF with exercises and class vocabulary.",
    urlLabel: "Link",
    urlPlaceholder: "https://drive.google.com/...",
    addButton: "Save material",
    materialsTitle: "Saved materials",
    materialsEmpty: "No materials yet. Add your first one above.",
    searchPlaceholder: "Search materials…",
    searchEmpty: "No materials match your search.",
    deleteLabel: "Delete",
    assignTitle: "Assign to students",
    assignHint: "Pick a student and mark the materials they can access.",
    studentLabel: "Student",
    studentPlaceholder: "Select a student",
    saveAssignments: "Save assignment",
    assigned: "Assigned",
    notAssigned: "Not assigned",
    assignAllLabel: "Assign to all",
    completedLabel: "Completed",
    successAdded: "Material saved.",
    successAssigned: "Assignment updated.",
    errorGeneric: "We couldn't complete that action. Please try again.",
    errorUrl: "The link must start with https://",
    errorTitle: "Enter a title with at least 2 characters.",
  },
};
