import type { StudentContent } from "./types";

export const en: StudentContent = {
  metadata: {
    studentTitle: "My student area",
    studentDescription: "Access materials and classes Paulina shared with you.",
    parentTitle: "Parent area",
    parentDescription: "Follow the linked student's classes and homework.",
    teacherTitle: "Teacher area",
    teacherDescription: "Manage homework, classes, and student/parent access.",
  },
  portal: {
    backHome: "Back to home",
    myArea: "My area",
    teacherArea: "Teacher area",
    signInTitle: "Sign in to your area",
    signInSubtitle: "Use the email address Paulina invited you with.",
    emailLabel: "Email",
    passwordLabel: "Password",
    signInButton: "Sign in",
    signInError: "Incorrect email or password.",
    logoutLabel: "Log out",
    languageToggleAria: "Change language",
    accountNavLabel: "Password",
    accountTitle: "Your password",
    accountHint:
      "If Paulina gave you a temporary password, change it here to one you'll remember.",
    accountCurrentLabel: "Current password",
    accountNewLabel: "New password",
    accountConfirmLabel: "Confirm new password",
    accountSaveButton: "Save password",
    accountMinHint: "At least 8 characters.",
    accountUpdated: "Done. You can now sign in with your new password.",
    accountErrorCurrent: "The current password is incorrect.",
    accountErrorShort: "The new password must be at least 8 characters.",
    accountErrorMismatch: "The passwords do not match.",
    accountErrorSame: "Choose a password different from the current one.",
    accountErrorGeneric: "We could not save the password. Please try again.",
  },
  student: {
    title: "Your classes and homework",
    subtitle: "See the date, time, Meet link, and homework for each class.",
    parentSubtitle: "Classes and homework for {name}",
    emptyTitle: "No classes yet",
    emptyBody: "When Paulina schedules classes or homework, they will show up here.",
    openLabel: "Open material",
    newBadge: "New",
    classesTitle: "Classes",
    upcomingTitle: "Upcoming classes",
    pastTitle: "Past classes",
    undatedTitle: "Other materials",
    scheduledLabel: "Class",
    joinMeetLabel: "Join Meet",
    homeworkLabel: "Homework",
    homeworkEmpty: "No homework for this class yet.",
    statusLabel: "Done?",
    statusPending: "Pending",
    statusDone: "Yes",
    statusNotDone: "No",
    statusPartial: "Partially",
    notesLabel: "Class notes",
    notesPlaceholder: "Write anything you want to remember from class…",
    notesSaved: "Notes saved",
    sessionRescheduled: "Rescheduled",
  },
  parent: {
    title: "{name}'s progress",
    titleFallback: "Your student's progress",
    subtitle:
      "See the linked student's classes and whether homework is done. Paulina marks the status after each class.",
    linkedLabel: "Linked student",
    unlinkedTitle: "No student is linked yet",
    unlinkedBody:
      "When Paulina links your account to a student, you will see their classes and whether homework was done.",
    statUpcoming: "Upcoming classes",
    statDone: "Homework done",
    statPending: "Homework pending",
    statOverdue: "Overdue homework",
    homeworkBarTitle: "Homework progress",
    homeworkBarEmpty: "No homework assigned yet.",
    attentionTitle: "Needs attention",
    attentionEmpty: "All caught up: no overdue homework.",
    nextClassTitle: "Next class",
    nextClassEmpty: "There is no upcoming class right now.",
    noHomework: "No homework",
  },
  teacher: {
    title: "Classes and homework",
    subtitle:
      "Pick a student: set their schedule, write homework on each class, and mark whether it was done.",
    selectStudentLabel: "Student",
    selectStudentPlaceholder: "Select a student",
    urlHint:
      "Materials without a class date (Drive, PDF, YouTube). Kept separate from the class table.",
    addTitle: "New extra material",
    titleLabel: "Title",
    titlePlaceholder: "Verb guide",
    descriptionLabel: "Description",
    descriptionPlaceholder: "Optional notes or instructions…",
    urlLabel: "Link (optional)",
    urlPlaceholder: "https://drive.google.com/...",
    urlOptionalHint: "PDF, Drive, or online resource.",
    nextClassHint:
      "Homework goes in each row of the class table. This section is only for undated materials.",
    scheduledAtLabel: "Class date and time",
    meetUrlLabel: "Google Meet link",
    meetUrlPlaceholder: "https://meet.google.com/...",
    addButton: "Save and assign",
    editButton: "Edit",
    saveEditButton: "Save changes",
    cancelEditButton: "Cancel",
    materialsTitle: "Extra materials",
    materialsEmpty: "No extra materials for this student.",
    classesTableTitle: "Class table",
    classesEmpty: "No classes yet. Save a fixed schedule or add a class.",
    homeworkLabel: "Homework for this class",
    homeworkPlaceholder: "Paste the exercise or note book and page…",
    saveHomeworkButton: "Save",
    addClassLabel: "Add class",
    addClassButton: "Create class",
    extrasTitle: "Extra materials",
    extrasHint: "Resources without a class date. Not mixed with homework.",
    extrasEmpty: "No extra materials yet.",
    upcomingTitle: "Upcoming",
    pastTitle: "Past",
    searchPlaceholder: "Search materials…",
    searchEmpty: "No materials match your search.",
    deleteLabel: "Delete",
    assignButton: "Assign",
    assignHint: "Assign this material to more students if needed.",
    assignAllLabel: "Assign to all",
    homeworkStatusLabel: "Done?",
    statusPending: "Pending",
    statusDone: "Yes",
    statusNotDone: "No",
    statusPartial: "Partially",
    noStudents: "No students yet. Create them under People.",
    scheduleSectionTitle: "Schedule and Meet",
    scheduleSectionHint:
      "Add one or more days with a time, and how far ahead to create classes. The Meet link stays the same for every class. To move just one class, change that row in the table; the rest of the weekly plan stays. Saving builds those dates (homework is kept).",
    scheduleModeWeekly: "Fixed weekly schedule",
    scheduleModeAdhoc: "Class by class",
    scheduleWeekdayLabel: "Day",
    scheduleTimeLabel: "Time (24h, e.g. 20:00 = 8 pm)",
    scheduleSlotHeading: "Class {n}",
    scheduleAddSlot: "Add another class each week",
    scheduleRemoveSlot: "Remove",
    scheduleErrorDuplicateSlot: "Two classes cannot be on the same day at the same time.",
    scheduleErrorTooManySlots: "Up to 7 fixed classes per week.",
    scheduleErrorIncompleteSlot: "Each class needs a day and a time.",
    scheduleHorizonLabel: "Plan ahead",
    scheduleHorizonWeeks: "{weeks} weeks",
    scheduleHorizonMonths: "{weeks} weeks · {months} months",
    scheduleMeetLabel: "Meet (same link every time)",
    scheduleSaveLabel: "Save schedule",
    scheduleActiveLabel: "Generate upcoming classes",
    scheduleSaved:
      "Schedule saved. Upcoming classes are on the calendar; you can add homework on each date.",
    calendarTitle: "Calendar",
    calendarHint:
      "Use the arrows to see the next month. Tap a time to jump to that class and add homework.",
    calendarPrevMonth: "Previous month",
    calendarNextMonth: "Next month",
    calendarToday: "Today",
    calendarEmptyMonth: "No classes this month.",
    calendarMore: "+{count} more",
    calendarSessionAria: "Go to the {time} class",
    weekdaySunday: "Sunday",
    weekdayMonday: "Monday",
    weekdayTuesday: "Tuesday",
    weekdayWednesday: "Wednesday",
    weekdayThursday: "Thursday",
    weekdayFriday: "Friday",
    weekdaySaturday: "Saturday",
    createStudentTitle: "New student",
    studentNameLabel: "Name",
    studentNamePlaceholder: "Anna Gomez",
    studentEmailLabel: "Email",
    studentEmailPlaceholder: "anna@email.com",
    studentPasswordLabel: "Initial password",
    studentPasswordPlaceholder: "At least 8 characters",
    createStudentButton: "Create student",
    successStudentCreated: "Student created.",
    createParentTitle: "New parent account",
    parentNameLabel: "Name",
    parentNamePlaceholder: "Mary Gomez",
    parentEmailLabel: "Email",
    parentEmailPlaceholder: "mary@email.com",
    parentPasswordLabel: "Initial password",
    parentPasswordPlaceholder: "At least 8 characters",
    parentStudentLabel: "Linked student",
    createParentButton: "Create parent account",
    successParentCreated: "Parent account created.",
    errorStudentName: "Enter a name with at least 2 characters.",
    errorStudentEmail: "Enter a valid email address.",
    errorStudentPassword: "The password must be at least 8 characters.",
    errorParentName: "Enter a name with at least 2 characters.",
    errorParentEmail: "Enter a valid email address.",
    errorParentPassword: "The password must be at least 8 characters.",
    errorParentStudent: "Select a student.",
    successAdded: "Material saved and assigned.",
    successAssigned: "Assignment updated.",
    successUpdated: "Changes saved.",
    successClassAdded: "Class added.",
    errorGeneric: "We could not complete that action. Please try again.",
    errorUrl: "The link must start with https://",
    errorTitle: "Enter a title with at least 2 characters.",
    errorContent: "Add a description or a link.",
    errorClassDate: "Choose a class date and time.",
    sessionErrorTimeConflict: "There is already a class at that date and time.",
    sessionRescheduled: "Rescheduled",
    navMaterials: "Materials",
    navStudents: "Students",
    navLeads: "Leads",
    navContacts: "Contacts",
    navEmails: "Emails",
    navSignature: "Signature",
    navUsers: "Users",
    navAria: "Teacher area sections",
    navSubAria: "Subsections",
    navGroupClasses: "Classes",
    navGroupAnalytics: "Overview",
    navGroupPeople: "People",
    navGroupCrm: "CRM",
    navGroupMail: "Mail",
    studentsCreateCta: "Create accounts",
    usersTitle: "Users",
    usersSubtitle: "Create and manage admin, teacher, student, and parent accounts.",
    usersEmpty: "No users yet.",
    usersCreateTitle: "New user",
    usersEditTitle: "Edit user",
    usersNameLabel: "Name",
    usersEmailLabel: "Email",
    usersRoleLabel: "Role",
    usersPasswordLabel: "Password",
    usersPasswordSectionTitle: "Change password",
    usersNewPasswordLabel: "New password",
    usersPasswordConfirmLabel: "Confirm password",
    usersPasswordSaveButton: "Update password",
    usersPasswordHint: "At least 8 characters.",
    usersPasswordUpdated: "Password updated.",
    usersActiveLabel: "Active account",
    usersStudentLinkLabel: "Linked student",
    usersStudentLinkEmpty: "Create a student first to link this parent.",
    usersCreateButton: "Create user",
    usersSaveButton: "Save changes",
    usersDeactivateButton: "Deactivate",
    usersActivateButton: "Activate",
    usersDeleteButton: "Delete permanently",
    usersDeleteConfirm: "Delete this user permanently? This cannot be undone.",
    usersBackLabel: "Back to users",
    usersRoleAdmin: "Admin",
    usersRoleTeacher: "Teacher",
    usersRoleStudent: "Student",
    usersRoleParent: "Parent",
    usersStatusActive: "Active",
    usersStatusInactive: "Inactive",
    usersErrorGeneric: "Could not save. Check the details and try again.",
    usersErrorSelf: "You cannot deactivate, demote, or delete your own account.",
    usersErrorLastAdmin: "At least one active admin is required.",
    usersErrorParentStudent: "Choose a student to link to this parent.",
    usersErrorPassword: "The password must be at least 8 characters.",
    usersErrorPasswordMismatch: "The passwords do not match.",
    studentsTitle: "Students",
    studentsSubtitle:
      "Student list with parent email (when linked) and class schedule. Open one to assign homework.",
    studentsEmpty: "No active students yet.",
    studentsNameLabel: "Name",
    studentsEmailLabel: "Email",
    studentsParentEmailLabel: "Parent email",
    studentsScheduleLabel: "Class schedule",
    studentsNoParent: "—",
    studentsNoSchedule: "No fixed schedule",
    studentsOpenHomework: "Assign homework",
    analyticsTitle: "Overview",
    analyticsSubtitle:
      "A quick look at this week's classes, homework, and what needs a follow-up.",
    analyticsWeekRange: "Week of {start} to {end}",
    analyticsStatClassesWeek: "Classes this week",
    analyticsStatClassesToday: "Today",
    analyticsStatHomeworkDone: "Homework done",
    analyticsStatHomeworkPending: "Homework pending",
    analyticsStatHomeworkOverdue: "Overdue homework",
    analyticsStatStudents: "Active students",
    analyticsStatNoUpcoming: "No upcoming class",
    analyticsStatNoParent: "No parent linked",
    analyticsStatUnread: "Unread messages",
    analyticsStatLeadsWeek: "Leads this week",
    analyticsHomeworkBarTitle: "Homework this week",
    analyticsHomeworkBarEmpty: "No homework assigned on this week's classes yet.",
    analyticsAgendaTitle: "Classes this week",
    analyticsAgendaEmpty: "No classes scheduled this week.",
    analyticsAttentionTitle: "Needs attention",
    analyticsAttentionEmpty: "Nothing pending right now.",
    analyticsHomeworkNone: "No homework",
    analyticsColWhen: "When",
    analyticsColStudent: "Student",
    analyticsColHomework: "Homework",
    analyticsColNeed: "What's missing",
    analyticsOpenLabel: "Open",
    analyticsNeedsOverdue: "Overdue homework ({when})",
    analyticsNeedsNoClass: "No upcoming class",
  },
  mail: {
    homeworkSubject: "Paulina assigned you homework",
    homeworkBody: "Paulina added homework for {title}.",
    materialSubject: "Paulina shared a material with you",
    materialBody: "Paulina assigned this material: {title}.",
    parentHomeworkSubject: "New homework for {studentName}",
    parentHomeworkBody: "Paulina added homework for {studentName}: {title}.",
    parentMaterialSubject: "New material for {studentName}",
    parentMaterialBody: "Paulina assigned a material to {studentName}: {title}.",
    greeting: "Hi {name},",
    whenLabel: "Class: {when}",
    previewLabel: "Homework:",
    ctaLabel: "Open your area",
    footer: "If the button does not work, go to {url}",
  },
};
