import type { StudentContent } from "./types";

export const es: StudentContent = {
  metadata: {
    studentTitle: "Mi área de alumno",
    studentDescription: "Accede a los materiales y clases que Paulina compartió contigo.",
    parentTitle: "Área de madre/padre",
    parentDescription: "Sigue las clases y los deberes del alumno vinculado.",
    teacherTitle: "Área de profesora",
    teacherDescription: "Gestiona deberes, clases y acceso de alumnos y padres.",
  },
  portal: {
    backHome: "Volver al inicio",
    myArea: "Mi área",
    teacherArea: "Área de profesora",
    signInTitle: "Entra a tu área",
    signInSubtitle: "Usa el correo con el que te invitó Paulina.",
    emailLabel: "Correo",
    passwordLabel: "Contraseña",
    signInButton: "Entrar",
    signInError: "Correo o contraseña incorrectos.",
    logoutLabel: "Salir",
    languageToggleAria: "Cambiar idioma",
    accountNavLabel: "Contraseña",
    accountTitle: "Tu contraseña",
    accountHint:
      "Si Paulina te dio una clave provisional, cámbiala aquí por una que recuerdes.",
    accountCurrentLabel: "Contraseña actual",
    accountNewLabel: "Nueva contraseña",
    accountConfirmLabel: "Confirmar nueva contraseña",
    accountSaveButton: "Guardar contraseña",
    accountMinHint: "Mínimo 8 caracteres.",
    accountUpdated: "Listo. Ya puedes entrar con tu nueva contraseña.",
    accountErrorCurrent: "La contraseña actual no es correcta.",
    accountErrorShort: "La nueva contraseña debe tener al menos 8 caracteres.",
    accountErrorMismatch: "Las contraseñas no coinciden.",
    accountErrorSame: "Elige una contraseña distinta a la actual.",
    accountErrorGeneric: "No pudimos guardar la contraseña. Inténtalo de nuevo.",
  },
  student: {
    title: "Tus clases y deberes",
    subtitle: "Aquí ves la fecha, la hora, el Meet y los deberes de cada clase.",
    parentSubtitle: "Clases y deberes de {name}",
    emptyTitle: "Aún no hay clases",
    emptyBody: "Cuando Paulina programe clases o deberes, aparecerán aquí.",
    openLabel: "Abrir material",
    newBadge: "Nuevo",
    classesTitle: "Clases",
    upcomingTitle: "Próximas clases",
    pastTitle: "Clases anteriores",
    undatedTitle: "Otros materiales",
    scheduledLabel: "Clase",
    joinMeetLabel: "Unirse a Meet",
    homeworkLabel: "Deberes",
    homeworkEmpty: "Todavía no hay deberes para esta clase.",
    statusLabel: "¿Hechos?",
    statusPending: "Pendiente",
    statusDone: "Sí",
    statusNotDone: "No",
    statusPartial: "Parcialmente",
    notesLabel: "Apuntes de clase",
    notesPlaceholder: "Escribe aquí lo que quieras recordar de la clase…",
    notesSaved: "Apuntes guardados",
    sessionRescheduled: "Reprogramada",
  },
  parent: {
    title: "El progreso de {name}",
    titleFallback: "El progreso de tu alumno",
    subtitle:
      "Aquí ves las clases del alumno vinculado y si ya hizo los deberes. Paulina marca el estado después de cada clase.",
    linkedLabel: "Alumno vinculado",
    unlinkedTitle: "Todavía no hay un alumno vinculado",
    unlinkedBody:
      "Cuando Paulina vincule tu cuenta con un alumno, aquí verás sus clases y si hizo los deberes.",
    statUpcoming: "Próximas clases",
    statDone: "Deberes hechos",
    statPending: "Deberes pendientes",
    statOverdue: "Deberes atrasados",
    homeworkBarTitle: "Cómo van los deberes",
    homeworkBarEmpty: "Todavía no hay deberes asignados.",
    attentionTitle: "Para revisar",
    attentionEmpty: "Todo al día: no hay deberes atrasados.",
    nextClassTitle: "Próxima clase",
    nextClassEmpty: "No hay una clase próxima por ahora.",
    noHomework: "Sin deberes",
  },
  teacher: {
    title: "Clases y deberes",
    subtitle:
      "Elige un alumno: configura el horario, escribe los deberes en cada clase y marca si los hicieron.",
    selectStudentLabel: "Alumno",
    selectStudentPlaceholder: "Selecciona un alumno",
    urlHint:
      "Materiales sin fecha de clase (Drive, PDF, YouTube). Quedan aparte de la tabla de clases.",
    addTitle: "Nuevo material extra",
    titleLabel: "Título",
    titlePlaceholder: "Guía de verbos",
    descriptionLabel: "Descripción",
    descriptionPlaceholder: "Notas o instrucciones opcionales…",
    urlLabel: "Enlace (opcional)",
    urlPlaceholder: "https://drive.google.com/...",
    urlOptionalHint: "PDF, Drive o recurso online.",
    nextClassHint:
      "Los deberes se escriben en cada fila de la tabla de clases. Aquí solo van materiales sin fecha.",
    scheduledAtLabel: "Fecha y hora de clase",
    meetUrlLabel: "Enlace a Google Meet",
    meetUrlPlaceholder: "https://meet.google.com/...",
    addButton: "Guardar y asignar",
    editButton: "Editar",
    saveEditButton: "Guardar cambios",
    cancelEditButton: "Cancelar",
    materialsTitle: "Materiales extra",
    materialsEmpty: "No hay materiales extra para este alumno.",
    classesTableTitle: "Tabla de clases",
    classesEmpty: "Todavía no hay clases. Guarda un horario fijo o añade una clase.",
    homeworkLabel: "Deberes de esta clase",
    homeworkPlaceholder: "Pega el ejercicio o escribe libro y página…",
    saveHomeworkButton: "Guardar",
    addClassLabel: "Añadir clase",
    addClassButton: "Crear clase",
    extrasTitle: "Materiales extra",
    extrasHint: "Recursos sin fecha de clase. No se mezclan con los deberes.",
    extrasEmpty: "Ningún material extra todavía.",
    upcomingTitle: "Próximos",
    pastTitle: "Anteriores",
    searchPlaceholder: "Buscar materiales…",
    searchEmpty: "Ningún material coincide con tu búsqueda.",
    deleteLabel: "Eliminar",
    assignButton: "Asignar",
    assignHint: "Asigna el material a más alumnos si hace falta.",
    assignAllLabel: "Asignar a todos",
    homeworkStatusLabel: "¿Hechos?",
    statusPending: "Pendiente",
    statusDone: "Sí",
    statusNotDone: "No",
    statusPartial: "Parcialmente",
    noStudents: "Todavía no hay alumnos. Créalos en Personas.",
    scheduleSectionTitle: "Horario y Meet",
    scheduleSectionHint:
      "Añade uno o más días con hora y hasta cuándo crear las clases. El Meet es el mismo enlace en todas. Si una semana hay que cambiar una clase, cambia solo esa fecha en la tabla; el resto del horario sigue igual. Al guardar se arman esas fechas (los deberes se conservan).",
    scheduleModeWeekly: "Horario fijo (cada semana)",
    scheduleModeAdhoc: "Clase a clase",
    scheduleWeekdayLabel: "Día",
    scheduleTimeLabel: "Hora (24h, ej. 20:00 = 8 pm)",
    scheduleSlotHeading: "Clase {n}",
    scheduleAddSlot: "Añadir otra clase en la semana",
    scheduleRemoveSlot: "Quitar",
    scheduleErrorDuplicateSlot: "Dos clases no pueden ser el mismo día a la misma hora.",
    scheduleErrorTooManySlots: "Como máximo 7 clases fijas por semana.",
    scheduleErrorIncompleteSlot: "Cada clase necesita día y hora.",
    scheduleHorizonLabel: "Planificar",
    scheduleHorizonWeeks: "{weeks} semanas",
    scheduleHorizonMonths: "{weeks} semanas · {months} meses",
    scheduleMeetLabel: "Meet (mismo enlace siempre)",
    scheduleSaveLabel: "Guardar horario",
    scheduleActiveLabel: "Generar próximas clases",
    scheduleSaved:
      "Horario guardado. Las próximas clases ya están en el calendario; ahora puedes cargar deberes en cada fecha.",
    calendarTitle: "Calendario",
    calendarHint:
      "Usa las flechas para ver el mes siguiente. Toca una hora para ir a esa clase y escribir los deberes.",
    calendarPrevMonth: "Mes anterior",
    calendarNextMonth: "Mes siguiente",
    calendarToday: "Hoy",
    calendarEmptyMonth: "No hay clases este mes.",
    calendarMore: "+{count} más",
    calendarSessionAria: "Ir a la clase de las {time}",
    weekdaySunday: "Domingo",
    weekdayMonday: "Lunes",
    weekdayTuesday: "Martes",
    weekdayWednesday: "Miércoles",
    weekdayThursday: "Jueves",
    weekdayFriday: "Viernes",
    weekdaySaturday: "Sábado",
    createStudentTitle: "Nuevo alumno",
    studentNameLabel: "Nombre",
    studentNamePlaceholder: "Ana Gómez",
    studentEmailLabel: "Correo",
    studentEmailPlaceholder: "ana@email.com",
    studentPasswordLabel: "Contraseña inicial",
    studentPasswordPlaceholder: "Mínimo 8 caracteres",
    createStudentButton: "Crear alumno",
    successStudentCreated: "Alumno creado.",
    createParentTitle: "Nuevo padre/madre",
    parentNameLabel: "Nombre",
    parentNamePlaceholder: "María Gómez",
    parentEmailLabel: "Correo",
    parentEmailPlaceholder: "maria@email.com",
    parentPasswordLabel: "Contraseña inicial",
    parentPasswordPlaceholder: "Mínimo 8 caracteres",
    parentStudentLabel: "Alumno vinculado",
    createParentButton: "Crear cuenta padre/madre",
    successParentCreated: "Cuenta de padre/madre creada.",
    errorStudentName: "Escribe un nombre de al menos 2 caracteres.",
    errorStudentEmail: "Escribe un correo válido.",
    errorStudentPassword: "La contraseña debe tener al menos 8 caracteres.",
    errorParentName: "Escribe un nombre de al menos 2 caracteres.",
    errorParentEmail: "Escribe un correo válido.",
    errorParentPassword: "La contraseña debe tener al menos 8 caracteres.",
    errorParentStudent: "Selecciona un alumno.",
    successAdded: "Material guardado y asignado.",
    successAssigned: "Asignación actualizada.",
    successUpdated: "Cambios guardados.",
    successClassAdded: "Clase añadida.",
    errorGeneric: "No pudimos completar la acción. Inténtalo de nuevo.",
    errorUrl: "El enlace debe empezar con https://",
    errorTitle: "Escribe un título de al menos 2 caracteres.",
    errorContent: "Añade una descripción o un enlace.",
    errorClassDate: "Elige fecha y hora de la clase.",
    sessionErrorTimeConflict: "Ya hay una clase en esa fecha y hora.",
    sessionRescheduled: "Reprogramada",
    navMaterials: "Materiales",
    navStudents: "Estudiantes",
    navLeads: "Leads",
    navContacts: "Contactos",
    navEmails: "Emails",
    navSignature: "Firma",
    navUsers: "Usuarios",
    navAria: "Secciones del área de profesora",
    navSubAria: "Subsecciones",
    navGroupClasses: "Clases",
    navGroupAnalytics: "Resumen",
    navGroupPeople: "Personas",
    navGroupCrm: "CRM",
    navGroupMail: "Correo",
    studentsCreateCta: "Crear cuentas",
    usersTitle: "Usuarios",
    usersSubtitle: "Crea y gestiona cuentas de admin, profe, alumno y padre.",
    usersEmpty: "Todavía no hay usuarios.",
    usersCreateTitle: "Nuevo usuario",
    usersEditTitle: "Editar usuario",
    usersNameLabel: "Nombre",
    usersEmailLabel: "Correo",
    usersRoleLabel: "Rol",
    usersPasswordLabel: "Contraseña",
    usersPasswordSectionTitle: "Cambiar contraseña",
    usersNewPasswordLabel: "Nueva contraseña",
    usersPasswordConfirmLabel: "Confirmar contraseña",
    usersPasswordSaveButton: "Actualizar contraseña",
    usersPasswordHint: "Mínimo 8 caracteres.",
    usersPasswordUpdated: "Contraseña actualizada.",
    usersActiveLabel: "Cuenta activa",
    usersStudentLinkLabel: "Alumno vinculado",
    usersStudentLinkEmpty: "Crea un alumno primero para poder vincular al padre/madre.",
    usersCreateButton: "Crear usuario",
    usersSaveButton: "Guardar cambios",
    usersDeactivateButton: "Desactivar",
    usersActivateButton: "Activar",
    usersDeleteButton: "Eliminar definitivamente",
    usersDeleteConfirm: "¿Eliminar este usuario de forma permanente? No se puede deshacer.",
    usersBackLabel: "Volver a usuarios",
    usersRoleAdmin: "Admin",
    usersRoleTeacher: "Profe",
    usersRoleStudent: "Alumno",
    usersRoleParent: "Padre/madre",
    usersStatusActive: "Activo",
    usersStatusInactive: "Inactivo",
    usersErrorGeneric: "No se pudo guardar. Revisa los datos e inténtalo de nuevo.",
    usersErrorSelf: "No puedes desactivar, degradar ni eliminar tu propia cuenta.",
    usersErrorLastAdmin: "Debe quedar al menos un admin activo.",
    usersErrorParentStudent: "Elige un alumno para vincular al padre/madre.",
    usersErrorPassword: "La contraseña debe tener al menos 8 caracteres.",
    usersErrorPasswordMismatch: "Las contraseñas no coinciden.",
    studentsTitle: "Estudiantes",
    studentsSubtitle:
      "Lista de alumnos con correo del padre (si aplica) y horario de clase. Abre uno para asignar deberes.",
    studentsEmpty: "Todavía no hay estudiantes activos.",
    studentsNameLabel: "Nombre",
    studentsEmailLabel: "Correo",
    studentsParentEmailLabel: "Correo del padre",
    studentsScheduleLabel: "Horario de clase",
    studentsNoParent: "—",
    studentsNoSchedule: "Sin horario fijo",
    studentsOpenHomework: "Asignar deberes",
    analyticsTitle: "Resumen",
    analyticsSubtitle:
      "Un vistazo rápido a las clases de esta semana, los deberes y lo que conviene revisar.",
    analyticsWeekRange: "Semana del {start} al {end}",
    analyticsStatClassesWeek: "Clases esta semana",
    analyticsStatClassesToday: "Hoy",
    analyticsStatHomeworkDone: "Deberes hechos",
    analyticsStatHomeworkPending: "Deberes pendientes",
    analyticsStatHomeworkOverdue: "Deberes atrasados",
    analyticsStatStudents: "Alumnos activos",
    analyticsStatNoUpcoming: "Sin clase próxima",
    analyticsStatNoParent: "Sin padre vinculado",
    analyticsStatUnread: "Mensajes sin leer",
    analyticsStatLeadsWeek: "Leads esta semana",
    analyticsHomeworkBarTitle: "Deberes de esta semana",
    analyticsHomeworkBarEmpty: "Todavía no hay deberes asignados en las clases de esta semana.",
    analyticsAgendaTitle: "Clases de esta semana",
    analyticsAgendaEmpty: "No hay clases programadas esta semana.",
    analyticsAttentionTitle: "Para revisar",
    analyticsAttentionEmpty: "Nada pendiente por ahora.",
    analyticsHomeworkNone: "Sin deberes",
    analyticsColWhen: "Cuándo",
    analyticsColStudent: "Alumno",
    analyticsColHomework: "Deberes",
    analyticsColNeed: "Qué falta",
    analyticsOpenLabel: "Ver",
    analyticsNeedsOverdue: "Deberes atrasados ({when})",
    analyticsNeedsNoClass: "No tiene clase próxima",
  },
  mail: {
    homeworkSubject: "Paulina te dejó deberes",
    homeworkBody: "Paulina cargó deberes para {title}.",
    materialSubject: "Paulina te compartió un material",
    materialBody: "Paulina te asignó este material: {title}.",
    parentHomeworkSubject: "Nuevos deberes para {studentName}",
    parentHomeworkBody: "Paulina cargó deberes para {studentName}: {title}.",
    parentMaterialSubject: "Nuevo material para {studentName}",
    parentMaterialBody: "Paulina asignó un material a {studentName}: {title}.",
    greeting: "Hola {name},",
    whenLabel: "Clase: {when}",
    previewLabel: "Deberes:",
    ctaLabel: "Ver en tu área",
    footer: "Si el botón no funciona, entra a {url}",
  },
};
