import type { StudentContent } from "./types";

export const es: StudentContent = {
  metadata: {
    studentTitle: "Mi área de alumno",
    studentDescription: "Accede a los materiales y clases que Paulina compartió contigo.",
    teacherTitle: "Área de profesora",
    teacherDescription: "Gestiona deberes, clases y acceso de alumnos y padres.",
  },
  portal: {
    backHome: "Volver al inicio",
    myArea: "Mi área",
    teacherArea: "Área de profesora",
    signInTitle: "Entra a tu área",
    signInSubtitle: "Usa el correo con el que te invitó Paulina.",
    emailLabel: "Correo",
    passwordLabel: "Contraseña",
    signInButton: "Entrar",
    signInError: "Correo o contraseña incorrectos.",
    logoutLabel: "Salir",
    languageToggleAria: "Cambiar idioma",
  },
  student: {
    title: "Tus clases y deberes",
    subtitle: "Aquí ves la fecha, la hora, el Meet y los deberes de cada clase.",
    parentSubtitle: "Clases y deberes de {name}",
    emptyTitle: "Aún no hay clases",
    emptyBody: "Cuando Paulina programe clases o deberes, aparecerán aquí.",
    openLabel: "Abrir material",
    newBadge: "Nuevo",
    classesTitle: "Clases",
    upcomingTitle: "Próximas clases",
    pastTitle: "Clases anteriores",
    undatedTitle: "Otros materiales",
    scheduledLabel: "Clase",
    joinMeetLabel: "Unirse a Meet",
    homeworkLabel: "Deberes",
    homeworkEmpty: "Todavía no hay deberes para esta clase.",
    statusLabel: "¿Hechos?",
    statusPending: "Pendiente",
    statusDone: "Sí",
    statusNotDone: "No",
    statusPartial: "Parcialmente",
    notesLabel: "Apuntes de clase",
    notesPlaceholder: "Escribe aquí lo que quieras recordar de la clase…",
    notesSaved: "Apuntes guardados",
  },
  teacher: {
    title: "Clases y deberes",
    subtitle:
      "Elige un alumno: configura el horario, escribe los deberes en cada clase y marca si los hicieron.",
    selectStudentLabel: "Alumno",
    selectStudentPlaceholder: "Selecciona un alumno",
    urlHint:
      "Materiales sin fecha de clase (Drive, PDF, YouTube). Quedan aparte de la tabla de clases.",
    addTitle: "Nuevo material extra",
    titleLabel: "Título",
    titlePlaceholder: "Guía de verbos",
    descriptionLabel: "Descripción",
    descriptionPlaceholder: "Notas o instrucciones opcionales…",
    urlLabel: "Enlace (opcional)",
    urlPlaceholder: "https://drive.google.com/...",
    urlOptionalHint: "PDF, Drive o recurso online.",
    nextClassHint:
      "Los deberes se escriben en cada fila de la tabla de clases. Aquí solo van materiales sin fecha.",
    scheduledAtLabel: "Fecha y hora de clase",
    meetUrlLabel: "Enlace a Google Meet",
    meetUrlPlaceholder: "https://meet.google.com/...",
    addButton: "Guardar y asignar",
    editButton: "Editar",
    saveEditButton: "Guardar cambios",
    cancelEditButton: "Cancelar",
    materialsTitle: "Materiales extra",
    materialsEmpty: "No hay materiales extra para este alumno.",
    classesTableTitle: "Tabla de clases",
    classesEmpty: "Todavía no hay clases. Guarda un horario fijo o añade una clase.",
    homeworkLabel: "Deberes de esta clase",
    homeworkPlaceholder: "Pega el ejercicio o escribe libro y página…",
    saveHomeworkButton: "Guardar",
    addClassLabel: "Añadir clase",
    addClassButton: "Crear clase",
    extrasTitle: "Materiales extra",
    extrasHint: "Recursos sin fecha de clase. No se mezclan con los deberes.",
    extrasEmpty: "Ningún material extra todavía.",
    upcomingTitle: "Próximos",
    pastTitle: "Anteriores",
    searchPlaceholder: "Buscar materiales…",
    searchEmpty: "Ningún material coincide con tu búsqueda.",
    deleteLabel: "Eliminar",
    assignButton: "Asignar",
    assignHint: "Asigna el material a más alumnos si hace falta.",
    assignAllLabel: "Asignar a todos",
    homeworkStatusLabel: "¿Hechos?",
    statusPending: "Pendiente",
    statusDone: "Sí",
    statusNotDone: "No",
    statusPartial: "Parcialmente",
    noStudents: "Todavía no hay alumnos. Créalos arriba para empezar.",
    scheduleSectionTitle: "Horario y Meet",
    scheduleSectionHint:
      "Horario fijo: al guardar, todas las clases futuras de este alumno pasan a ese día y hora (los deberes se conservan). Clase a clase: solo guardas el Meet y añades cada fecha. El enlace es siempre el mismo.",
    scheduleModeWeekly: "Horario fijo (cada semana)",
    scheduleModeAdhoc: "Clase a clase",
    scheduleWeekdayLabel: "Día",
    scheduleTimeLabel: "Hora (24h, ej. 20:00 = 8 pm)",
    scheduleMeetLabel: "Meet (mismo enlace siempre)",
    scheduleSaveLabel: "Guardar horario",
    scheduleActiveLabel: "Generar próximas clases",
    scheduleSaved: "Horario guardado. Todas las clases futuras quedaron con ese día y hora.",
    weekdaySunday: "Domingo",
    weekdayMonday: "Lunes",
    weekdayTuesday: "Martes",
    weekdayWednesday: "Miércoles",
    weekdayThursday: "Jueves",
    weekdayFriday: "Viernes",
    weekdaySaturday: "Sábado",
    createStudentTitle: "Nuevo alumno",
    studentNameLabel: "Nombre",
    studentNamePlaceholder: "Ana Gómez",
    studentEmailLabel: "Correo",
    studentEmailPlaceholder: "ana@email.com",
    studentPasswordLabel: "Contraseña inicial",
    studentPasswordPlaceholder: "Mínimo 8 caracteres",
    createStudentButton: "Crear alumno",
    successStudentCreated: "Alumno creado.",
    createParentTitle: "Nuevo padre/madre",
    parentNameLabel: "Nombre",
    parentNamePlaceholder: "María Gómez",
    parentEmailLabel: "Correo",
    parentEmailPlaceholder: "maria@email.com",
    parentPasswordLabel: "Contraseña inicial",
    parentPasswordPlaceholder: "Mínimo 8 caracteres",
    parentStudentLabel: "Alumno vinculado",
    createParentButton: "Crear cuenta padre/madre",
    successParentCreated: "Cuenta de padre/madre creada.",
    errorStudentName: "Escribe un nombre de al menos 2 caracteres.",
    errorStudentEmail: "Escribe un correo válido.",
    errorStudentPassword: "La contraseña debe tener al menos 8 caracteres.",
    errorParentName: "Escribe un nombre de al menos 2 caracteres.",
    errorParentEmail: "Escribe un correo válido.",
    errorParentPassword: "La contraseña debe tener al menos 8 caracteres.",
    errorParentStudent: "Selecciona un alumno.",
    successAdded: "Material guardado y asignado.",
    successAssigned: "Asignación actualizada.",
    successUpdated: "Cambios guardados.",
    successClassAdded: "Clase añadida.",
    errorGeneric: "No pudimos completar la acción. Inténtalo de nuevo.",
    errorUrl: "El enlace debe empezar con https://",
    errorTitle: "Escribe un título de al menos 2 caracteres.",
    errorContent: "Añade una descripción o un enlace.",
    errorClassDate: "Elige fecha y hora de la clase.",
    navMaterials: "Materiales",
    navStudents: "Estudiantes",
    navLeads: "Leads",
    navContacts: "Contactos",
    navEmails: "Emails",
    navSignature: "Firma",
    navUsers: "Usuarios",
    usersTitle: "Usuarios",
    usersSubtitle: "Crea y gestiona cuentas de admin, profe, alumno y padre.",
    usersEmpty: "Todavía no hay usuarios.",
    usersCreateTitle: "Nuevo usuario",
    usersEditTitle: "Editar usuario",
    usersNameLabel: "Nombre",
    usersEmailLabel: "Correo",
    usersRoleLabel: "Rol",
    usersPasswordLabel: "Contraseña",
    usersPasswordSectionTitle: "Cambiar contraseña",
    usersNewPasswordLabel: "Nueva contraseña",
    usersPasswordConfirmLabel: "Confirmar contraseña",
    usersPasswordSaveButton: "Actualizar contraseña",
    usersPasswordHint: "Mínimo 8 caracteres.",
    usersPasswordUpdated: "Contraseña actualizada.",
    usersActiveLabel: "Cuenta activa",
    usersStudentLinkLabel: "Alumno vinculado",
    usersCreateButton: "Crear usuario",
    usersSaveButton: "Guardar cambios",
    usersDeactivateButton: "Desactivar",
    usersActivateButton: "Activar",
    usersDeleteButton: "Eliminar definitivamente",
    usersDeleteConfirm: "¿Eliminar este usuario de forma permanente? No se puede deshacer.",
    usersBackLabel: "Volver a usuarios",
    usersRoleAdmin: "Admin",
    usersRoleTeacher: "Profe",
    usersRoleStudent: "Alumno",
    usersRoleParent: "Padre/madre",
    usersStatusActive: "Activo",
    usersStatusInactive: "Inactivo",
    usersErrorGeneric: "No se pudo guardar. Revisa los datos e inténtalo de nuevo.",
    usersErrorSelf: "No puedes desactivar, degradar ni eliminar tu propia cuenta.",
    usersErrorLastAdmin: "Debe quedar al menos un admin activo.",
    usersErrorParentStudent: "Elige un alumno para vincular al padre/madre.",
    usersErrorPassword: "La contraseña debe tener al menos 8 caracteres.",
    usersErrorPasswordMismatch: "Las contraseñas no coinciden.",
    studentsTitle: "Estudiantes",
    studentsSubtitle:
      "Lista de alumnos con correo del padre (si aplica) y horario de clase. Abre uno para asignar deberes.",
    studentsEmpty: "Todavía no hay estudiantes activos.",
    studentsNameLabel: "Nombre",
    studentsEmailLabel: "Correo",
    studentsParentEmailLabel: "Correo del padre",
    studentsScheduleLabel: "Horario de clase",
    studentsNoParent: "—",
    studentsNoSchedule: "Sin horario fijo",
    studentsOpenHomework: "Asignar deberes",
  },
};
