import type { StudentContent } from "./types";

export const es: StudentContent = {
  metadata: {
    studentTitle: "Mi área de alumno | Bilingual Boost",
    studentDescription: "Accede a los materiales que Paulina compartió contigo.",
    teacherTitle: "Área de profesora | Bilingual Boost",
    teacherDescription: "Gestiona materiales y asígnalos a tus alumnos.",
  },
  portal: {
    backHome: "Volver al inicio",
    myArea: "Mi área",
    teacherArea: "Área de profesora",
    signInTitle: "Entra a tu área",
    signInSubtitle: "Usa el correo con el que te invitó Paulina.",
  },
  student: {
    title: "Tus materiales",
    subtitle: "Aquí tienes los recursos que Paulina compartió contigo.",
    emptyTitle: "Aún no tienes materiales",
    emptyBody: "Cuando Paulina te asigne recursos, aparecerán aquí.",
    openLabel: "Abrir material",
    newBadge: "Nuevo",
    markDone: "Marcar como hecho",
    markUndone: "Marcar como pendiente",
    doneBadge: "Hecho",
  },
  teacher: {
    title: "Materiales para alumnos",
    subtitle: "Agrega enlaces (por ejemplo Google Drive) y asígnalos a cada alumno.",
    addTitle: "Nuevo material",
    titleLabel: "Título",
    titlePlaceholder: "Guía de conversación — semana 1",
    descriptionLabel: "Descripción",
    descriptionPlaceholder: "PDF con ejercicios y vocabulario de la clase.",
    urlLabel: "Enlace",
    urlPlaceholder: "https://drive.google.com/...",
    addButton: "Guardar material",
    materialsTitle: "Materiales guardados",
    materialsEmpty: "Todavía no hay materiales. Agrega el primero arriba.",
    searchPlaceholder: "Buscar materiales…",
    searchEmpty: "Ningún material coincide con tu búsqueda.",
    deleteLabel: "Eliminar",
    assignTitle: "Asignar a alumnos",
    assignHint: "Elige un alumno y marca los materiales que puede ver.",
    studentLabel: "Alumno",
    studentPlaceholder: "Selecciona un alumno",
    saveAssignments: "Guardar asignación",
    assigned: "Asignado",
    notAssigned: "Sin asignar",
    assignAllLabel: "Asignar a todos",
    completedLabel: "Completado",
    successAdded: "Material guardado.",
    successAssigned: "Asignación actualizada.",
    errorGeneric: "No pudimos completar la acción. Inténtalo de nuevo.",
    errorUrl: "El enlace debe empezar con https://",
    errorTitle: "Escribe un título de al menos 2 caracteres.",
  },
};
