import type { StudentContent } from "./types";

export const pl: StudentContent = {
  metadata: {
    studentTitle: "Moja strefa ucznia",
    studentDescription: "Uzyskaj dostęp do materiałów i zajęć udostępnionych przez Paulinę.",
    parentTitle: "Strefa rodzica",
    parentDescription: "Śledź zajęcia i zadania powiązanego ucznia.",
    teacherTitle: "Strefa nauczycielki",
    teacherDescription: "Zarządzaj zadaniami, zajęciami i dostępem uczniów oraz rodziców.",
  },
  portal: {
    backHome: "Wróć na stronę główną",
    myArea: "Moja strefa",
    teacherArea: "Strefa nauczycielki",
    signInTitle: "Zaloguj się do swojej strefy",
    signInSubtitle: "Użyj adresu e-mail, na który zaprosiła Cię Paulina.",
    emailLabel: "E-mail",
    passwordLabel: "Hasło",
    signInButton: "Zaloguj się",
    signInError: "Nieprawidłowy e-mail lub hasło.",
    logoutLabel: "Wyloguj się",
    languageToggleAria: "Zmień język",
    accountNavLabel: "Hasło",
    accountTitle: "Twoje hasło",
    accountHint:
      "Jeśli Paulina dała Ci hasło tymczasowe, zmień je tutaj na takie, które zapamiętasz.",
    accountCurrentLabel: "Obecne hasło",
    accountNewLabel: "Nowe hasło",
    accountConfirmLabel: "Potwierdź nowe hasło",
    accountSaveButton: "Zapisz hasło",
    accountMinHint: "Minimum 8 znaków.",
    accountUpdated: "Gotowe. Możesz już logować się nowym hasłem.",
    accountErrorCurrent: "Obecne hasło jest nieprawidłowe.",
    accountErrorShort: "Nowe hasło musi mieć co najmniej 8 znaków.",
    accountErrorMismatch: "Hasła nie są takie same.",
    accountErrorSame: "Wybierz hasło inne niż obecne.",
    accountErrorGeneric: "Nie udało się zapisać hasła. Spróbuj ponownie.",
  },
  student: {
    title: "Twoje zajęcia i zadania",
    subtitle: "Zobacz datę, godzinę, Meet i zadania do każdej lekcji.",
    parentSubtitle: "Zajęcia i zadania: {name}",
    emptyTitle: "Brak zajęć",
    emptyBody: "Gdy Paulina zaplanuje zajęcia lub zadania, pojawią się tutaj.",
    openLabel: "Otwórz materiał",
    newBadge: "Nowe",
    classesTitle: "Zajęcia",
    upcomingTitle: "Nadchodzące zajęcia",
    pastTitle: "Poprzednie zajęcia",
    undatedTitle: "Inne materiały",
    scheduledLabel: "Zajęcia",
    joinMeetLabel: "Dołącz do Meet",
    homeworkLabel: "Zadania",
    homeworkEmpty: "Brak zadań do tych zajęć.",
    statusLabel: "Zrobione?",
    statusPending: "Oczekuje",
    statusDone: "Tak",
    statusNotDone: "Nie",
    statusPartial: "Częściowo",
    notesLabel: "Notatki z zajęć",
    notesPlaceholder: "Zapisz tu to, co chcesz zapamiętać z zajęć…",
    notesSaved: "Notatki zapisane",
    sessionRescheduled: "Przełożone",
  },
  parent: {
    title: "Postępy: {name}",
    titleFallback: "Postępy Twojego ucznia",
    subtitle:
      "Tutaj widzisz zajęcia powiązanego ucznia i czy zadania są zrobione. Paulina oznacza status po każdych zajęciach.",
    linkedLabel: "Powiązany uczeń",
    unlinkedTitle: "Nie ma jeszcze powiązanego ucznia",
    unlinkedBody:
      "Gdy Paulina powiąże Twoje konto z uczniem, zobaczysz tu zajęcia i czy zadania zostały zrobione.",
    statUpcoming: "Nadchodzące zajęcia",
    statDone: "Zadania zrobione",
    statPending: "Zadania oczekujące",
    statOverdue: "Zadania zaległe",
    homeworkBarTitle: "Jak idą zadania",
    homeworkBarEmpty: "Nie ma jeszcze przypisanych zadań.",
    attentionTitle: "Do sprawdzenia",
    attentionEmpty: "Wszystko na bieżąco: brak zaległych zadań.",
    nextClassTitle: "Najbliższe zajęcia",
    nextClassEmpty: "Nie ma teraz nadchodzących zajęć.",
    noHomework: "Brak zadań",
  },
  teacher: {
    title: "Zajęcia i zadania",
    subtitle:
      "Wybierz ucznia: ustaw harmonogram, wpisz zadania przy każdej lekcji i oznacz, czy zostały zrobione.",
    selectStudentLabel: "Uczeń",
    selectStudentPlaceholder: "Wybierz ucznia",
    urlHint:
      "Materiały bez daty zajęć (Drive, PDF, YouTube). Osobno od tabeli zajęć.",
    addTitle: "Nowy materiał dodatkowy",
    titleLabel: "Tytuł",
    titlePlaceholder: "Przewodnik czasowników",
    descriptionLabel: "Opis",
    descriptionPlaceholder: "Opcjonalne notatki lub instrukcje…",
    urlLabel: "Link (opcjonalnie)",
    urlPlaceholder: "https://drive.google.com/...",
    urlOptionalHint: "PDF, Drive lub materiał online.",
    nextClassHint:
      "Zadania wpisujesz w wierszach tabeli zajęć. Ta sekcja jest tylko na materiały bez daty.",
    scheduledAtLabel: "Data i godzina zajęć",
    meetUrlLabel: "Link Google Meet",
    meetUrlPlaceholder: "https://meet.google.com/...",
    addButton: "Zapisz i przypisz",
    editButton: "Edytuj",
    saveEditButton: "Zapisz zmiany",
    cancelEditButton: "Anuluj",
    materialsTitle: "Materiały dodatkowe",
    materialsEmpty: "Brak materiałów dodatkowych dla tego ucznia.",
    classesTableTitle: "Tabela zajęć",
    classesEmpty: "Brak zajęć. Zapisz stały harmonogram albo dodaj lekcję.",
    homeworkLabel: "Zadania do tych zajęć",
    homeworkPlaceholder: "Wklej ćwiczenie albo podręcznik i stronę…",
    saveHomeworkButton: "Zapisz",
    addClassLabel: "Dodaj zajęcia",
    addClassButton: "Utwórz zajęcia",
    extrasTitle: "Materiały dodatkowe",
    extrasHint: "Zasoby bez daty zajęć. Nie mieszają się z zadaniami.",
    extrasEmpty: "Brak materiałów dodatkowych.",
    upcomingTitle: "Nadchodzące",
    pastTitle: "Poprzednie",
    searchPlaceholder: "Szukaj materiałów…",
    searchEmpty: "Brak materiałów pasujących do wyszukiwania.",
    deleteLabel: "Usuń",
    assignButton: "Przypisz",
    assignHint: "Przypisz ten materiał innym uczniom, jeśli trzeba.",
    assignAllLabel: "Przypisz wszystkim",
    homeworkStatusLabel: "Zrobione?",
    statusPending: "Oczekuje",
    statusDone: "Tak",
    statusNotDone: "Nie",
    statusPartial: "Częściowo",
    noStudents: "Nie ma jeszcze uczniów. Utwórz ich w Osoby.",
    scheduleSectionTitle: "Harmonogram i Meet",
    scheduleSectionHint:
      "Dodaj jeden lub wiecej dni z godzina i jak daleko do przodu utworzyc zajecia. Link Meet jest zawsze ten sam. Jesli trzeba przesunac jedna lekcje, zmien tylko te date w tabeli; reszta harmonogramu zostaje. Zapis tworzy te daty (zadania zostaja).",
    scheduleModeWeekly: "Stały harmonogram tygodniowy",
    scheduleModeAdhoc: "Z lekcji na lekcję",
    scheduleWeekdayLabel: "Dzień",
    scheduleTimeLabel: "Godzina (24h, np. 20:00 = 8pm)",
    scheduleSlotHeading: "Zajęcia {n}",
    scheduleAddSlot: "Dodaj kolejne zajęcia w tygodniu",
    scheduleRemoveSlot: "Usuń",
    scheduleErrorDuplicateSlot:
      "Dwie lekcje nie mogą być tego samego dnia o tej samej godzinie.",
    scheduleErrorTooManySlots: "Maksymalnie 7 stałych zajęć w tygodniu.",
    scheduleErrorIncompleteSlot: "Każde zajęcia potrzebują dnia i godziny.",
    scheduleHorizonLabel: "Zaplanuj",
    scheduleHorizonWeeks: "{weeks} tygodni",
    scheduleHorizonMonths: "{weeks} tygodni · {months} mies.",
    scheduleMeetLabel: "Meet (ten sam link zawsze)",
    scheduleSaveLabel: "Zapisz harmonogram",
    scheduleActiveLabel: "Generuj nadchodzące zajęcia",
    scheduleSaved:
      "Harmonogram zapisany. Najblizsze zajecia sa w kalendarzu; teraz mozesz dodac zadania do kazdej daty.",
    calendarTitle: "Kalendarz",
    calendarHint:
      "Uzyj strzalek, aby zobaczyc nastepny miesiac. Dotknij godziny, aby przejsc do zajec i wpisac zadania.",
    calendarPrevMonth: "Poprzedni miesiąc",
    calendarNextMonth: "Następny miesiąc",
    calendarToday: "Dziś",
    calendarEmptyMonth: "Brak zajęć w tym miesiącu.",
    calendarMore: "+{count} więcej",
    calendarSessionAria: "Przejdź do zajęć o {time}",
    weekdaySunday: "Niedziela",
    weekdayMonday: "Poniedziałek",
    weekdayTuesday: "Wtorek",
    weekdayWednesday: "Środa",
    weekdayThursday: "Czwartek",
    weekdayFriday: "Piątek",
    weekdaySaturday: "Sobota",
    createStudentTitle: "Nowy uczeń",
    studentNameLabel: "Imię i nazwisko",
    studentNamePlaceholder: "Anna Gomez",
    studentEmailLabel: "E-mail",
    studentEmailPlaceholder: "anna@email.com",
    studentPasswordLabel: "Hasło początkowe",
    studentPasswordPlaceholder: "Minimum 8 znaków",
    createStudentButton: "Utwórz ucznia",
    successStudentCreated: "Uczeń został utworzony.",
    createParentTitle: "Nowe konto rodzica",
    parentNameLabel: "Imię i nazwisko",
    parentNamePlaceholder: "Maria Gomez",
    parentEmailLabel: "E-mail",
    parentEmailPlaceholder: "maria@email.com",
    parentPasswordLabel: "Hasło początkowe",
    parentPasswordPlaceholder: "Minimum 8 znaków",
    parentStudentLabel: "Powiązany uczeń",
    createParentButton: "Utwórz konto rodzica",
    successParentCreated: "Konto rodzica utworzone.",
    errorStudentName: "Wpisz imię i nazwisko o długości co najmniej 2 znaków.",
    errorStudentEmail: "Wpisz prawidłowy adres e-mail.",
    errorStudentPassword: "Hasło musi mieć co najmniej 8 znaków.",
    errorParentName: "Wpisz imię i nazwisko o długości co najmniej 2 znaków.",
    errorParentEmail: "Wpisz prawidłowy adres e-mail.",
    errorParentPassword: "Hasło musi mieć co najmniej 8 znaków.",
    errorParentStudent: "Wybierz ucznia.",
    successAdded: "Materiał zapisany i przypisany.",
    successAssigned: "Przypisanie zaktualizowane.",
    successUpdated: "Zmiany zapisane.",
    successClassAdded: "Zajęcia dodane.",
    errorGeneric: "Nie udało się wykonać operacji. Spróbuj ponownie.",
    errorUrl: "Link musi zaczynać się od https://",
    errorTitle: "Wpisz tytuł o długości co najmniej 2 znaków.",
    errorContent: "Dodaj opis lub link.",
    errorClassDate: "Wybierz datę i godzinę zajęć.",
    sessionErrorTimeConflict: "Są już zajęcia w tej dacie i godzinie.",
    sessionRescheduled: "Przełożone",
    navMaterials: "Materialy",
    navStudents: "Studenci",
    navLeads: "Leady",
    navContacts: "Wiadomosci",
    navEmails: "E-maile",
    navSignature: "Podpis",
    navUsers: "Uzytkownicy",
    navAria: "Sekcje strefy nauczycielki",
    navSubAria: "Podsekcje",
    navGroupClasses: "Zajecia",
    navGroupAnalytics: "Przeglad",
    navGroupPeople: "Osoby",
    navGroupCrm: "CRM",
    navGroupMail: "Poczta",
    studentsCreateCta: "Utworz konta",
    usersTitle: "Uzytkownicy",
    usersSubtitle: "Tworz i zarzadzaj kontami admina, nauczyciela, ucznia i rodzica.",
    usersEmpty: "Brak uzytkownikow.",
    usersCreateTitle: "Nowy uzytkownik",
    usersEditTitle: "Edytuj uzytkownika",
    usersNameLabel: "Imie i nazwisko",
    usersEmailLabel: "E-mail",
    usersRoleLabel: "Rola",
    usersPasswordLabel: "Haslo",
    usersPasswordSectionTitle: "Zmien haslo",
    usersNewPasswordLabel: "Nowe haslo",
    usersPasswordConfirmLabel: "Potwierdz haslo",
    usersPasswordSaveButton: "Zaktualizuj haslo",
    usersPasswordHint: "Minimum 8 znakow.",
    usersPasswordUpdated: "Haslo zaktualizowane.",
    usersActiveLabel: "Konto aktywne",
    usersStudentLinkLabel: "Powiazany uczen",
    usersStudentLinkEmpty: "Najpierw utworz ucznia, aby powiazac rodzica.",
    usersCreateButton: "Utworz uzytkownika",
    usersSaveButton: "Zapisz zmiany",
    usersDeactivateButton: "Dezaktywuj",
    usersActivateButton: "Aktywuj",
    usersDeleteButton: "Usun trwale",
    usersDeleteConfirm: "Usunac tego uzytkownika na stale? Tej operacji nie mozna cofnac.",
    usersBackLabel: "Wroc do uzytkownikow",
    usersRoleAdmin: "Admin",
    usersRoleTeacher: "Nauczyciel",
    usersRoleStudent: "Uczen",
    usersRoleParent: "Rodzic",
    usersStatusActive: "Aktywny",
    usersStatusInactive: "Nieaktywny",
    usersErrorGeneric: "Nie udalo sie zapisac. Sprawdz dane i sprobuj ponownie.",
    usersErrorSelf: "Nie mozesz dezaktywowac, zmienic roli ani usunac wlasnego konta.",
    usersErrorLastAdmin: "Musi pozostac co najmniej jeden aktywny admin.",
    usersErrorParentStudent: "Wybierz ucznia do powiazania z rodzicem.",
    usersErrorPassword: "Haslo musi miec co najmniej 8 znakow.",
    usersErrorPasswordMismatch: "Hasla nie sa takie same.",
    studentsTitle: "Studenci",
    studentsSubtitle:
      "Lista uczniow z e-mailem rodzica (jesli jest) i godzina zajec. Otworz, aby zadac prace domowa.",
    studentsEmpty: "Brak aktywnych studentow.",
    studentsNameLabel: "Imie",
    studentsEmailLabel: "E-mail",
    studentsParentEmailLabel: "E-mail rodzica",
    studentsScheduleLabel: "Godzina zajec",
    studentsNoParent: "—",
    studentsNoSchedule: "Brak stalego planu",
    studentsOpenHomework: "Zadaj prace",
    analyticsTitle: "Przeglad",
    analyticsSubtitle:
      "Szybki przeglad zajec w tym tygodniu, zadan i tego, co warto sprawdzic.",
    analyticsWeekRange: "Tydzien od {start} do {end}",
    analyticsStatClassesWeek: "Zajecia w tym tygodniu",
    analyticsStatClassesToday: "Dzis",
    analyticsStatHomeworkDone: "Zadania zrobione",
    analyticsStatHomeworkPending: "Zadania oczekujace",
    analyticsStatHomeworkOverdue: "Zadania zalegle",
    analyticsStatStudents: "Aktywni uczniowie",
    analyticsStatNoUpcoming: "Bez nastepnych zajec",
    analyticsStatNoParent: "Bez rodzica",
    analyticsStatUnread: "Nieprzeczytane wiadomosci",
    analyticsStatLeadsWeek: "Leady w tym tygodniu",
    analyticsHomeworkBarTitle: "Zadania w tym tygodniu",
    analyticsHomeworkBarEmpty: "W tym tygodniu nie ma jeszcze zadanych prac.",
    analyticsAgendaTitle: "Zajecia w tym tygodniu",
    analyticsAgendaEmpty: "Brak zaplanowanych zajec w tym tygodniu.",
    analyticsAttentionTitle: "Do sprawdzenia",
    analyticsAttentionEmpty: "Nic nie wymaga teraz uwagi.",
    analyticsHomeworkNone: "Brak zadan",
    analyticsColWhen: "Kiedy",
    analyticsColStudent: "Uczen",
    analyticsColHomework: "Zadania",
    analyticsColNeed: "Czego brakuje",
    analyticsOpenLabel: "Otworz",
    analyticsNeedsOverdue: "Zalegle zadania ({when})",
    analyticsNeedsNoClass: "Brak nastepnych zajec",
  },
};
