import type { StudentContent } from "./types";

export const pl: StudentContent = {
  metadata: {
    studentTitle: "Moja strefa ucznia",
    studentDescription: "Uzyskaj dostęp do materiałów udostępnionych przez Paulinę.",
    teacherTitle: "Strefa nauczycielki",
    teacherDescription: "Zarządzaj materiałami i przypisuj je uczniom.",
  },
  portal: {
    backHome: "Wróć na stronę główną",
    myArea: "Moja strefa",
    teacherArea: "Strefa nauczycielki",
    signInTitle: "Zaloguj się do swojej strefy",
    signInSubtitle: "Użyj adresu e-mail, na który zaprosiła Cię Paulina.",
    emailLabel: "E-mail",
    passwordLabel: "Hasło",
    signInButton: "Zaloguj się",
    signInError: "Nieprawidłowy e-mail lub hasło.",
    logoutLabel: "Wyloguj się",
  },
  student: {
    title: "Twoje materiały",
    subtitle: "Tutaj znajdziesz zasoby udostępnione przez Paulinę.",
    emptyTitle: "Brak materiałów",
    emptyBody: "Gdy Paulina przypisze Ci zasoby, pojawią się tutaj.",
    openLabel: "Otwórz materiał",
    newBadge: "Nowy",
    markDone: "Oznacz jako ukończone",
    markUndone: "Oznacz jako oczekujące",
    doneBadge: "Ukończone",
  },
  teacher: {
    title: "Materiały dla uczniów",
    subtitle: "Dodaj linki (np. Google Drive) i przypisz je każdemu uczniowi.",
    addTitle: "Nowy materiał",
    titleLabel: "Tytuł",
    titlePlaceholder: "Przewodnik konwersacyjny — tydzień 1",
    descriptionLabel: "Opis",
    descriptionPlaceholder: "PDF z ćwiczeniami i słownictwem z lekcji.",
    urlLabel: "Link",
    urlPlaceholder: "https://drive.google.com/...",
    addButton: "Zapisz materiał",
    materialsTitle: "Zapisane materiały",
    materialsEmpty: "Brak materiałów. Dodaj pierwszy powyżej.",
    searchPlaceholder: "Szukaj materiałów…",
    searchEmpty: "Brak materiałów pasujących do wyszukiwania.",
    deleteLabel: "Usuń",
    assignButton: "Przypisz",
    assignHint: "Kliknij ucznia, aby przypisać lub cofnąć ten materiał.",
    assignAllLabel: "Przypisz wszystkim",
    completedLabel: "Ukończone",
    noStudents: "Nie ma jeszcze utworzonych uczniów. Dodaj ich tutaj, aby zacząć przypisywać materiały.",
    createStudentTitle: "Nowy uczeń",
    studentNameLabel: "Imię i nazwisko",
    studentNamePlaceholder: "Anna Gomez",
    studentEmailLabel: "E-mail",
    studentEmailPlaceholder: "anna@email.com",
    studentPasswordLabel: "Hasło początkowe",
    studentPasswordPlaceholder: "Minimum 8 znaków",
    createStudentButton: "Utwórz ucznia",
    successStudentCreated: "Uczeń został utworzony.",
    errorStudentName: "Wpisz imię i nazwisko o długości co najmniej 2 znaków.",
    errorStudentEmail: "Wpisz prawidłowy adres e-mail.",
    errorStudentPassword: "Hasło musi mieć co najmniej 8 znaków.",
    successAdded: "Materiał zapisany.",
    successAssigned: "Przypisanie zaktualizowane.",
    errorGeneric: "Nie udało się wykonać operacji. Spróbuj ponownie.",
    errorUrl: "Link musi zaczynać się od https://",
    errorTitle: "Wpisz tytuł o długości co najmniej 2 znaków.",
    navMaterials: "Materialy",
    navLeads: "Leady",
    navContacts: "Wiadomosci",
    navEmails: "E-maile",
    navSignature: "Podpis",
  },
};
