import type { StudentContent } from "./types";

export const pl: StudentContent = {
  metadata: {
    studentTitle: "Moja strefa ucznia",
    studentDescription: "Uzyskaj dostęp do materiałów i zajęć udostępnionych przez Paulinę.",
    teacherTitle: "Strefa nauczycielki",
    teacherDescription: "Zarządzaj zadaniami, zajęciami i dostępem uczniów oraz rodziców.",
  },
  portal: {
    backHome: "Wróć na stronę główną",
    myArea: "Moja strefa",
    teacherArea: "Strefa nauczycielki",
    signInTitle: "Zaloguj się do swojej strefy",
    signInSubtitle: "Użyj adresu e-mail, na który zaprosiła Cię Paulina.",
    emailLabel: "E-mail",
    passwordLabel: "Hasło",
    signInButton: "Zaloguj się",
    signInError: "Nieprawidłowy e-mail lub hasło.",
    logoutLabel: "Wyloguj się",
    languageToggleAria: "Zmień język",
  },
  student: {
    title: "Twoje materiały",
    subtitle: "Tutaj znajdziesz zadania i materiały udostępnione przez Paulinę.",
    parentSubtitle: "Materiały i zajęcia: {name}",
    emptyTitle: "Brak materiałów",
    emptyBody: "Gdy Paulina przypisze zadania, pojawią się tutaj.",
    openLabel: "Otwórz materiał",
    newBadge: "Nowe",
    upcomingTitle: "Nadchodzące zajęcia",
    pastTitle: "Poprzednie zajęcia",
    undatedTitle: "Inne materiały",
    scheduledLabel: "Zajęcia",
    joinMeetLabel: "Dołącz do Meet",
    statusLabel: "Zadanie",
    statusPending: "Oczekuje na sprawdzenie",
    statusDone: "Tak",
    statusNotDone: "Nie",
    statusPartial: "Częściowo",
    notesLabel: "Notatki z zajęć",
    notesPlaceholder: "Zapisz tu to, co chcesz zapamiętać z zajęć…",
    notesSaved: "Notatki zapisane",
  },
  teacher: {
    title: "Zadania i zajęcia",
    subtitle:
      "Wklej ćwiczenie w opisie (lub opcjonalny link), ustaw datę i przypisz uczniom.",
    urlHint:
      "Możesz wkleić całe ćwiczenie w opisie albo podać podręcznik i stronę. Link zewnętrzny jest opcjonalny.",
    addTitle: "Nowe zadanie",
    titleLabel: "Tytuł",
    titlePlaceholder: "Czasowniki — tydzień 1",
    descriptionLabel: "Ćwiczenie / opis",
    descriptionPlaceholder: "Wklej tutaj ćwiczenie albo napisz: Podręcznik X, strona 12…",
    urlLabel: "Link zewnętrzny (opcjonalnie)",
    urlPlaceholder: "https://drive.google.com/...",
    urlOptionalHint: "Tylko jeśli jest PDF lub materiał online. Nie jest wymagany do przypisania.",
    scheduledAtLabel: "Data i godzina zajęć",
    meetUrlLabel: "Link Google Meet (opcjonalnie)",
    meetUrlPlaceholder: "https://meet.google.com/...",
    addButton: "Zapisz zadanie",
    editButton: "Edytuj",
    saveEditButton: "Zapisz zmiany",
    cancelEditButton: "Anuluj",
    materialsTitle: "Zapisane zadania",
    materialsEmpty: "Brak zadań. Dodaj pierwsze powyżej.",
    upcomingTitle: "Nadchodzące",
    pastTitle: "Poprzednie",
    searchPlaceholder: "Szukaj zadań…",
    searchEmpty: "Brak zadań pasujących do wyszukiwania.",
    deleteLabel: "Usuń",
    assignButton: "Przypisz",
    assignHint: "Przypisz zadanie i oznacz, czy zostało wykonane.",
    assignAllLabel: "Przypisz wszystkim",
    homeworkStatusLabel: "Status zadania",
    statusPending: "Oczekuje",
    statusDone: "Tak",
    statusNotDone: "Nie",
    statusPartial: "Częściowo",
    noStudents: "Nie ma jeszcze utworzonych uczniów. Dodaj ich tutaj, aby zacząć przypisywać zadania.",
    scheduleSectionTitle: "Stały harmonogram ucznia",
    scheduleSectionHint:
      "Jeśli zajęcia są zawsze w ten sam dzień i godzinę, system tworzy kolejne sesje. Ty tylko przypisujesz lub edytujesz zadania. Jedną datę możesz zmienić w razie potrzeby.",
    scheduleWeekdayLabel: "Dzień",
    scheduleTimeLabel: "Godzina",
    scheduleMeetLabel: "Meet (ten sam link co tydzień)",
    scheduleSaveLabel: "Zapisz harmonogram",
    scheduleActiveLabel: "Aktywny",
    scheduleSaved: "Harmonogram zapisany. Utworzono nadchodzące zajęcia.",
    weekdaySunday: "Niedziela",
    weekdayMonday: "Poniedziałek",
    weekdayTuesday: "Wtorek",
    weekdayWednesday: "Środa",
    weekdayThursday: "Czwartek",
    weekdayFriday: "Piątek",
    weekdaySaturday: "Sobota",
    createStudentTitle: "Nowy uczeń",
    studentNameLabel: "Imię i nazwisko",
    studentNamePlaceholder: "Anna Gomez",
    studentEmailLabel: "E-mail",
    studentEmailPlaceholder: "anna@email.com",
    studentPasswordLabel: "Hasło początkowe",
    studentPasswordPlaceholder: "Minimum 8 znaków",
    createStudentButton: "Utwórz ucznia",
    successStudentCreated: "Uczeń został utworzony.",
    createParentTitle: "Nowe konto rodzica",
    parentNameLabel: "Imię i nazwisko",
    parentNamePlaceholder: "Maria Gomez",
    parentEmailLabel: "E-mail",
    parentEmailPlaceholder: "maria@email.com",
    parentPasswordLabel: "Hasło początkowe",
    parentPasswordPlaceholder: "Minimum 8 znaków",
    parentStudentLabel: "Powiązany uczeń",
    createParentButton: "Utwórz konto rodzica",
    successParentCreated: "Konto rodzica utworzone.",
    errorStudentName: "Wpisz imię i nazwisko o długości co najmniej 2 znaków.",
    errorStudentEmail: "Wpisz prawidłowy adres e-mail.",
    errorStudentPassword: "Hasło musi mieć co najmniej 8 znaków.",
    errorParentName: "Wpisz imię i nazwisko o długości co najmniej 2 znaków.",
    errorParentEmail: "Wpisz prawidłowy adres e-mail.",
    errorParentPassword: "Hasło musi mieć co najmniej 8 znaków.",
    errorParentStudent: "Wybierz ucznia.",
    successAdded: "Zadanie zapisane.",
    successAssigned: "Przypisanie zaktualizowane.",
    successUpdated: "Zmiany zapisane.",
    errorGeneric: "Nie udało się wykonać operacji. Spróbuj ponownie.",
    errorUrl: "Link musi zaczynać się od https://",
    errorTitle: "Wpisz tytuł o długości co najmniej 2 znaków.",
    errorContent: "Wpisz ćwiczenie w opisie lub dodaj link.",
    navMaterials: "Materialy",
    navLeads: "Leady",
    navContacts: "Wiadomosci",
    navEmails: "E-maile",
    navSignature: "Podpis",
  },
};
